
neo4j:
  image: neo4j:latest
  ports:
    - "7474:7474"
    - "7687:7687"

scope:
  image: weaveworks/scope:1.10.2
  net: "host"
  pid: "host"
  privileged: true
  labels:
    - "works.weave.role=system"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
  command:
    - "--probe.docker=true"

