artillery run demo/artillery/test/long_peaks.yml -o execution_results/long_peaks_without_1
artillery run demo/artillery/test/long_peaks.yml -o execution_results/long_peaks_without_2
artillery run demo/artillery/test/long_peaks.yml -o execution_results/long_peaks_without_3
artillery run demo/artillery/test/small_peaks_node_removal.yml -o execution_results/small_peaks_node_remove_1
artillery run demo/artillery/test/small_peaks_node_removal.yml -o execution_results/small_peaks_node_remove_2
artillery run demo/artillery/test/small_peaks_node_removal.yml -o execution_results/small_peaks_node_remove_3
artillery run demo/artillery/test/increasing.yml -o execution_results/increasing_1
artillery run demo/artillery/test/decreasing.yml -o execution_results/decreasing_1
artillery run demo/artillery/test/increasing.yml -o execution_results/increasing_2
artillery run demo/artillery/test/decreasing.yml -o execution_results/decreasing_2
artillery run demo/artillery/test/increasing.yml -o execution_results/increasing_3
artillery run demo/artillery/test/decreasing.yml -o execution_results/decreasing_4
