{
 "title": "Overview-2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CPU_COST", "label": "CPU cost per core per hour", "query": "0.0280" },
   { "name": "MEMORY_COST", "label": "Memory per GB cost per hour", "query": "0.0038" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load on php-apache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes received" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface=\"eth0\",pod_name=~\"php-apache-.*\"}[150s]))",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Number of php-apache pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Number of pods" }
   ],
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\", namespace=\"demo\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Cost nodes per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "currencyEUR", "label": "Cost per hour" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_num_cpu:sum) * $CPU_COST + sum(node:node_memory_bytes_total:sum) * ($MEMORY_COST / 2^30)",
     "legendFormat": "All nodes"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total CPU usage vs provisioned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode!=\"idle\",\n                  mode!=\"iowait\",\n                  mode!~\"^(?:guest.*)$\"\n                  }[1m]))",
     "legendFormat": "used"
    },
    { "expr": "sum(node:node_num_cpu:sum)", "legendFormat": "available" },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "CPU requested per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores requested" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores used" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode!=\"idle\",\n                  mode!=\"iowait\",\n                  mode!~\"^(?:guest.*)$\"\n                  }[150s])) BY (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage php-apache pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores used" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image=\"\", pod_name=~\"php-apache-.*\"}[150s])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage per pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Cores used" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\"}[150s])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total memory usage vs provisioned",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    { "expr": "sum(node_memory_Active)", "legendFormat": "used" },
    {
     "expr": "sum(node:node_memory_bytes_total:sum)",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Memory requested per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 21 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory requested" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory used per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Memory used" }
   ],
   "targets": [
    { "expr": "node_memory_Active", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory usage php-apache pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Memory used" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image=\"\", pod_name=~\"php-apache-.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "Memory used" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{container_name!=\"POD\",container_name!=\"\",pod_name!=\"\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}